- name: Install Debug Tools
  hosts: "*"
  become: true
  tasks:
  - name: install dependencies
    apt:
      name: 
       - git
       - curl 
       - vim 
       - lsb-release
       - jq
       - manpages-dev
       - unzip
      state: present
      update_cache: true
    become: true
  - name: install jq
    shell: |
      curl -L https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -o /usr/local/bin/jq
      chmod +x /usr/local/bin/jq
  - name: install yh
    shell: |
      curl -L https://github.com/andreazorzetto/yh/releases/download/v0.4.0/yh-linux-amd64.zip -o yh.zip
      unzip yh.zip
      mv yh /usr/local/bin/yh
      chmod +x /usr/local/bin/yh
  - name: install kubectl
    shell: |
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      mv kubectl /usr/local/bin/
  - name: install helm
    shell: |
      curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      chmod 700 get_helm.sh
      ./get_helm.sh
