- name: Install Goat
  hosts: "*"
  become: true
  tasks:
  - name: Install Goat
    shell: |
      kind create cluster --name goat
      git clone https://github.com/madhuakula/kubernetes-goat.git
      cd ./kubernetes-goat/kind-setup
      bash setup-kind-cluster-and-goat.sh
