- name: Install Ngrok
  hosts: "*"
  become: true
  tasks:
  - name: install kind
    shell: |
      curl -L https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.tgz -o ~/Downloads/ngrok-stable-linux-amd64.tgz
      sudo tar xvzf ~/Downloads/ngrok-stable-linux-amd64.tgz -C /usr/local/bin